# Useful methods or functions
include ../shared-makefile/cpp-constants.mk
include ../shared-makefile/npm-constants.mk
include ../shared-makefile/shared-cli.mk

all: $(NPM_SUCCESS)

include ../shared-makefile/npm-rules.mk